### ISSUE TITLE
Use Gson 2.2.4 instead of Gson 2.2.2

### ISSUE THREAD

**Issue by Niterux** [OrnitheMC/ploceus#2]
I am having issues with the config in my mod loading because 2.2.2 uses broken deserialization, manually changing the Gson version in my Prism Launcher instance fixed this so I think that Gson should be upgraded to 2.2.4 assuming there's no breaking changes it made.

**Comment by SpaceWalkerRS** [comment]
implemented in v1.5.6

**Comment by SpaceWalkerRS** [comment]
I used v2.10 instead - it's the most recent version used by MC as far as I can tell
